# Generated by Django 5.0 on 2025-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presentes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presente",
            name="imagem_base64",
            field=models.TextField(
                blank=True, help_text="Imagem codificada em base64", null=True
            ),
        ),
        migrations.AddField(
            model_name="presente",
            name="imagem_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome original do arquivo",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presente",
            name="imagem_tipo",
            field=models.CharField(
                blank=True, help_text="MIME type da imagem", max_length=50, null=True
            ),
        ),
    ]
