# Generated by Django 5.0 on 2026-02-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presentes", "0003_grupos_sistema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grupomembro",
            options={
                "ordering": ["-e_mantenedor", "-data_entrada"],
                "verbose_name": "Membro do Grupo",
                "verbose_name_plural": "Membros dos Grupos",
            },
        ),
        migrations.RenameIndex(
            model_name="grupomembro",
            new_name="grupomembro_grupo_usuario_idx",
            old_name="grupomembro_grupo_user_idx",
        ),
        migrations.RenameIndex(
            model_name="grupomembro",
            new_name="grupomembro_usuario_data_idx",
            old_name="grupomembro_user_data_idx",
        ),
        migrations.AlterField(
            model_name="compra",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo ao qual a compra pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compras",
                to="presentes.grupo",
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="codigo_convite",
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="imagem_base64",
            field=models.TextField(blank=True, help_text="Imagem codificada em base64", null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="imagem_nome",
            field=models.CharField(
                blank=True, help_text="Nome original do arquivo", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="imagem_tipo",
            field=models.CharField(
                blank=True, help_text="MIME type da imagem", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="grupomembro",
            name="e_mantenedor",
            field=models.BooleanField(
                default=False, help_text="Mantenedores podem gerenciar o grupo e seus membros"
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo ao qual a notificacao pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="presentes.grupo",
            ),
        ),
        migrations.AlterField(
            model_name="presente",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo ao qual o presente pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentes",
                to="presentes.grupo",
            ),
        ),
        migrations.AlterField(
            model_name="sugestaocompra",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo ao qual a sugestao pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sugestoes",
                to="presentes.grupo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="grupo_ativo",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo atualmente selecionado pelo usuario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_ativos",
                to="presentes.grupo",
            ),
        ),
        migrations.AddIndex(
            model_name="grupomembro",
            index=models.Index(
                fields=["grupo", "e_mantenedor"], name="grupomembro_grupo_manten_idx"
            ),
        ),
    ]
