# Generated by Django 5.1.9 on 2026-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presentes", "0007_precohistorico_pesquisaprecolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sugestaocompra",
            name="titulo_produto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titulo do produto no resultado da busca, para conferir se e o mesmo item",
                max_length=300,
            ),
        ),
    ]
